export const CartActionTypes = {
  TOGGLE_CART_DROPDOWN: 'TOGGLE_CART_DROPDOWN',
  ADD_ITEM: 'ADD_ITEM',
  REMOVE_ITEM: 'REMOVE_ITEM',
  DECREASE_QTY: 'DECREASE_QTY',
  CLEAR_CART: 'CLEAR_CART',
  SET_CART_FROM_FIREBASE: 'SET_CART_FROM_FIREBASE',
  UPDATE_CART_IN_FIREBASE: 'UPDATE_CART_IN_FIREBASE'
};
